// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klkncqrjpvvzwyoqmhfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsa25jcXJqcHZ2end5b3FtaGZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzg2MjMsImV4cCI6MjA1OTY1NDYyM30.IYsPNfLW7ruV2APNYxAcWo5sXhqIxJ-LMaToU2wzgy0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);